### ISSUE TITLE
current AMS compatibility due ?>

### ISSUE THREAD

**Issue by pwsincd** [bakatrouble/sys-screenuploader#1]
will you be altering titles to contents soon ?

**Comment by bakatrouble** [comment]
I'm not sure what you mean.
Moving a directory from `/atmosphere/titles` to `/atmosphere/contents`?
I've copied directory structure from another sysmodule release, but on my console it perfectly works from `contents` directory (the module doesn't appear in Kosmos Toolbox otherwise).
If you can confirm that `contents` directory works for stock Atmosphere as well, I'll rearrange release package, no problem.

**Comment by bakatrouble** [comment]
Okay, I've found a mention of this in Atmosphere release notes.
